<!DOCTYPE html>
<html>
<head>
    <title>Currículum de Javier Torres Martínez</title>
    <link rel="stylesheet" type="text/css" href="estilo.css">
</head>
<body>
    <h1>Javier Alejandro Torres Martínez</h1>
    <p><strong>Dirección:</strong> Américo Villarreal 300</p>
    <p><strong>Número de teléfono:</strong> 899-108-9590</p>
    <p><strong>Correo electrónico:</strong> javielo717@gmail.com</p>

    <h2>Objetivo</h2>
    <p>Creecer y aprender sobre las tecnologías de la información y comunicación (TICs).</p>

    <h2>Habilidades</h2>
    <ul>
        <li>Inglés</li>
        <li>Uso de tecnologías y software</li>
        <li>Conocimientos en programación</li>
        <li>Experiencia en reparación de dispositivos</li>
        <li>Habilidades en el manejo de computadoras</li>
    </ul>

    <h2>Experiencia laboral</h2>
    <p><strong>Técnico en una papelería</strong><br>
    Duración: 2 años<br>
    [Descripción detallada de tus responsabilidades y logros en este trabajo]</p>

    <h2>Educación</h2>
    <p><strong>Preparatoria [Nombre de la preparatoria]</strong><br>
    Año de graduación: [Año]</p>
    <p><strong>Universidad [Nombre de la universidad]</strong><br>
    Carrera: [Nombre de tu carrera]<br>
    Año de inicio: [Año actual]</p>

    <h2>Habilidades adicionales</h2>
    <p>Reparación de dispositivos electrónicos y computadoras</p>

    <h2>Pasatiempos</h2>
    <p>Videojuegos, lectura, pintura</p>

    <h2>Referencias</h2>
    <p>Referencia por parte de Alejandro Sáenz</p>

    <h2>Proyectos</h2>
    <p><a href="#" id="toggleButton">Mostrar/Ocultar Proyectos</a></p>
    <div id="hiddenContent" style="display: none;">
        <!-- Contenido de proyectos que se muestra/oculta -->
    </div>

    <script src="script.js"></script>
</body>
</html>
