---
nombre: Javier Alejandro Torres Martínez
direccion: Américo Villarreal 300
telefono: 899-108-9590
correo: javielo717@gmail.com
objetivo: Crecer y aprender sobre las tecnologías de la información y comunicación (TICs)
habilidades:
  - Inglés
  - Uso de tecnologías y software
  - Conocimientos en programación
  - Experiencia en reparación de dispositivos
  - Habilidades en el manejo de computadoras
experiencia_laboral:
  - puesto: Técnico en una papelería
    duracion: 2 años
    descripcion: [Descripción detallada de tus responsabilidades y logros en este trabajo]
educacion:
  - nivel: Preparatoria
    nombre: [Nombre de la preparatoria]
    ano_graduacion: [Año]
  - nivel: Universidad
    nombre: [Nombre de la universidad]
    carrera: [Nombre de tu carrera]
    ano_inicio: [Año actual]
habilidades_adicionales: Reparación de dispositivos electrónicos y computadoras
pasatiempos: Videojuegos, lectura, pintura
referencias: Referencia por parte de Alejandro Sáenz
---
